// SPDX-License-Identifier: GPL-3.0-only
// Copyright (c) 2026 Blinds Nisa. All rights reserved.

/**
 * Public route group — mounted at `/public`, NO authentication.
 * Access is gated entirely by the unguessable UUID `public_token` in
 * the URL (capability-style), and the routes never exist for tokens
 * that were not generated by a real send.
 *
 * Endpoints:
 *   GET  /estimate/:token          customer-facing estimate view data
 *   POST /estimate/:token/confirm  one-shot confirm (rate-limited)
 *
 * The confirm endpoint validates status='sent' (409 for double
 * confirms), stamps confirmed_at, and fires an internal notification
 * email — notification failure is logged but never blocks the
 * customer's confirmation. Both endpoints apply the defensive expiry
 * check so a stale 'sent' estimate reads as expired even if the daily
 * cron hasn't run yet.
 */

import { Hono } from 'hono';
import type { SupabaseClient } from '@supabase/supabase-js';
import { createSupabaseAdmin } from '../lib/supabase';
import { rateLimit } from '../middleware/rateLimit';
import { sendEmail, buildConfirmationNoticeHtml } from '../lib/email';
import type { Env } from '../index';

const app = new Hono<{ Bindings: Env }>();

/** UUID v4 shape — reject junk tokens before touching the DB. */
const TOKEN_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Rate limit everything under /public (5 requests/min/IP). */
app.use('*', rateLimit(5, 60_000));

/** Loads an estimate (+items/customer) by public token, or null. */
async function loadByToken(sb: SupabaseClient, token: string) {
  const { data } = await sb
    .from('estimates')
    .select('*, line_items(*), customer:customers(*)')
    .eq('public_token', token)
    .order('position', { referencedTable: 'line_items' })
    .maybeSingle();
  return data;
}

/** Defensive expiry: flips stale 'sent' estimates to expired in the DB. */
async function effectiveStatus(
  sb: SupabaseClient,
  estimate: { id: string; status: string; expiry_date: string }
): Promise<string> {
  const today = new Date().toISOString().slice(0, 10);
  if (estimate.status === 'sent' && estimate.expiry_date < today) {
    await sb.from('estimates').update({ status: 'expired' }).eq('id', estimate.id);
    return 'expired';
  }
  return estimate.status;
}

/** Public estimate view — everything the CustomerView page renders. */
app.get('/estimate/:token', async (c) => {
  const token = c.req.param('token');
  if (!TOKEN_RE.test(token)) return c.json({ error: 'Estimate not found' }, 404);

  const sb = createSupabaseAdmin(c.env);
  const estimate = await loadByToken(sb, token);
  if (!estimate) return c.json({ error: 'Estimate not found' }, 404);
  const status = await effectiveStatus(sb, estimate);

  const { data: company } = await sb
    .from('company_settings')
    .select('company_name, logo_url, email, phone, address, hst_number')
    .eq('id', 1)
    .single();

  // Sanitized payload: only what the customer page needs.
  return c.json({
    data: {
      status,
      order_number: estimate.order_number,
      estimate_date: estimate.estimate_date,
      expiry_date: estimate.expiry_date,
      subtotal: estimate.subtotal,
      discount_amount: estimate.discount_amount,
      taxable_amount: estimate.taxable_amount,
      tax_rate: estimate.tax_rate,
      tax_amount: estimate.tax_amount,
      total: estimate.total,
      terms: estimate.terms_snapshot ?? '',
      confirmed_at: estimate.confirmed_at,
      customer: {
        first_name: estimate.customer?.first_name ?? '',
        last_name: estimate.customer?.last_name ?? '',
        shipping_address_line1: estimate.customer?.shipping_address_line1 ?? '',
        shipping_address_line2: estimate.customer?.shipping_address_line2 ?? '',
        shipping_city: estimate.customer?.shipping_city ?? '',
        shipping_province: estimate.customer?.shipping_province ?? '',
        shipping_postal_code: estimate.customer?.shipping_postal_code ?? '',
      },
      company,
      line_items: (estimate.line_items ?? []).map((li: Record<string, unknown>) => ({
        item_type: li.item_type,
        room_name: li.room_name,
        blinds_type: li.blinds_type,
        panels: li.panels,
        height_cm: li.height_cm,
        fabric_name: li.fabric_name,
        cassette_name: li.cassette_name,
        control_name: li.control_name,
        description: li.description,
        quantity: li.quantity,
        unit_price: li.unit_price,
        line_total: li.line_total,
      })),
    },
  });
});

/**
 * Customer confirm — succeeds exactly once per estimate.
 * 404 unknown token · 409 already confirmed · 410 expired · 400 draft.
 */
app.post('/estimate/:token/confirm', async (c) => {
  const token = c.req.param('token');
  if (!TOKEN_RE.test(token)) return c.json({ error: 'Estimate not found' }, 404);

  const sb = createSupabaseAdmin(c.env);
  const estimate = await loadByToken(sb, token);
  if (!estimate) return c.json({ error: 'Estimate not found' }, 404);

  const status = await effectiveStatus(sb, estimate);
  if (status === 'confirmed') {
    return c.json({ error: 'This estimate has already been confirmed.' }, 409);
  }
  if (status === 'expired') {
    return c.json({ error: 'This estimate has expired. Please contact us for a new quote.' }, 410);
  }
  if (status !== 'sent') {
    return c.json({ error: 'This estimate cannot be confirmed yet.' }, 400);
  }

  // Guard the transition at the DB level too: only a 'sent' row updates,
  // so two racing confirms produce exactly one winner.
  const { data: updated, error } = await sb
    .from('estimates')
    .update({ status: 'confirmed', confirmed_at: new Date().toISOString() })
    .eq('id', estimate.id)
    .eq('status', 'sent')
    .select('id, total, order_number')
    .maybeSingle();
  if (error) return c.json({ error: error.message }, 500);
  if (!updated) return c.json({ error: 'This estimate has already been confirmed.' }, 409);

  // Internal notification — best effort, never blocks the customer.
  try {
    const { data: company } = await sb
      .from('company_settings')
      .select('email, company_name')
      .eq('id', 1)
      .single();
    if (company?.email) {
      await sendEmail(c.env, {
        to: company.email,
        subject: `✅ Estimate ${updated.order_number} confirmed`,
        html: buildConfirmationNoticeHtml({
          orderNumber: updated.order_number,
          customerName: `${estimate.customer?.first_name ?? ''} ${estimate.customer?.last_name ?? ''}`.trim(),
          total: Number(updated.total),
        }),
      });
    }
  } catch (e) {
    console.error('Confirmation notification failed:', e);
  }

  return c.json({ data: { status: 'confirmed', total: Number(updated.total) } });
});

export default app;
