// SPDX-License-Identifier: GPL-3.0-only
// Copyright (c) 2026 Blinds Nisa. All rights reserved.

/**
 * Public route group — mounted at `/public`, NO authentication.
 * Access is gated entirely by the unguessable UUID `public_token` in
 * the URL (capability-style), and the routes never exist for tokens
 * that were not generated by a real send.
 *
 * The customer sees an ESTIMATE (the document we emailed) even though
 * the underlying record is an ORDER. Confirming it moves the order
 * `sent → awaiting_payment` and stamps `confirmed_at`. After that the
 * SAME url keeps working as a live order summary — status tracker,
 * balance and e-Transfer details — which is why no status-update emails
 * are sent to customers.
 *
 * Endpoints:
 *   GET  /estimate/:token          customer-facing order/estimate view data
 *   POST /estimate/:token/confirm  one-shot confirm (rate-limited)
 *   POST /estimate/:token/cancel-request   ask to cancel the confirmation
 *   POST /estimate/:token/cancel-withdraw  take that request back
 *   GET  /appointment/:token       visit proposal (estimate or install)
 *   POST /appointment/:token/confirm  confirm the proposed window
 *   POST /appointment/:token/request  ask for a different time (+note)
 *
 * The confirm endpoint validates status='sent' (409 once it has moved
 * on), stamps confirmed_at, and fires an internal notification email —
 * notification failure is logged but never blocks the customer's
 * confirmation. Both endpoints apply the defensive expiry check so a
 * stale 'sent' order reads as expired even if the daily cron hasn't
 * run yet.
 *
 * NOTE (task: reversible confirmations): the customer can confirm but
 * can NEVER reverse — undoing a confirmation is a user-only action on
 * the authenticated `/api/orders/:id/unconfirm` route. The most a
 * customer can do is REQUEST cancellation here; the request is a flag
 * on the order (`cancel_requested_at`) and changes no status by itself.
 * Staff answer it on `/api/orders/:id/cancel-request/resolve`.
 */

import { Hono } from 'hono';
import type { SupabaseClient } from '@supabase/supabase-js';
import { createSupabaseAdmin } from '../lib/supabase';
import { rateLimit } from '../middleware/rateLimit';
import {
  sendEmail,
  buildConfirmationNoticeHtml,
  buildInstallationNoticeHtml,
  buildAppointmentNoticeHtml,
  buildCancellationNoticeHtml,
} from '../lib/email';
import type { Env } from '../index';

const app = new Hono<{ Bindings: Env }>();

/** UUID v4 shape — reject junk tokens before touching the DB. */
const TOKEN_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Rate limit everything under /public (5 requests/min/IP). */
app.use('*', rateLimit(5, 60_000));

/**
 * Loads an order (+items/customer/payments) by public token, or null.
 *
 * The `payments(amount)` embed exists solely so the Worker can compute
 * paid-to-date and the outstanding balance server-side — individual
 * payment rows are NEVER exposed to the customer, only the two totals
 * (see the sanitized payload below).
 */
async function loadByToken(sb: SupabaseClient, token: string) {
  const { data } = await sb
    .from('orders')
    .select('*, line_items(*), customer:customers(*), payments(amount)')
    .eq('public_token', token)
    .order('position', { referencedTable: 'line_items' })
    .maybeSingle();
  return data;
}

/**
 * Sums a payments embed into paid-to-date. Mirrors `sumPayments` in
 * `routes/orders.ts`; kept local because the public payload deliberately
 * shares no code path (and no shape) with the authenticated detail
 * response.
 */
function sumPayments(payments: Array<{ amount: number | string }> | null | undefined): number {
  return (payments ?? []).reduce((acc, p) => acc + Number(p.amount), 0);
}

/** Statuses in which a confirmation still exists to be cancelled. */
const CANCELLABLE_STATUS = 'awaiting_payment';

/**
 * Internal notice when a customer opens or withdraws a cancellation
 * request. Best effort in the established `/public` style: staff also
 * see an open request as a red banner on the order page, so a failed
 * send is logged and never surfaces to the customer.
 */
async function notifyCancellationRequest(
  env: Env,
  order: Record<string, any>,
  withdrawn: boolean,
  note?: string
): Promise<void> {
  try {
    const sb = createSupabaseAdmin(env);
    const { data: company } = await sb
      .from('company_settings')
      .select('email, company_name')
      .eq('id', 1)
      .single();
    if (!company?.email) return;
    const customerName =
      `${order.customer?.first_name ?? ''} ${order.customer?.last_name ?? ''}`.trim();
    await sendEmail(env, {
      to: company.email,
      subject: withdrawn
        ? `↩️ Cancellation request withdrawn — ${order.order_number}`
        : `⚠️ Cancellation requested — ${order.order_number}`,
      html: buildCancellationNoticeHtml({
        orderNumber: order.order_number,
        customerName,
        total: Number(order.total),
        withdrawn,
        note,
      }),
    });
  } catch (e) {
    console.error('Cancellation notification failed:', e);
  }
}

/** Defensive expiry: flips stale 'sent' orders to expired in the DB. */
async function effectiveStatus(
  sb: SupabaseClient,
  order: { id: string; status: string; expiry_date: string }
): Promise<string> {
  const today = new Date().toISOString().slice(0, 10);
  if (order.status === 'sent' && order.expiry_date < today) {
    await sb.from('orders').update({ status: 'expired' }).eq('id', order.id);
    return 'expired';
  }
  return order.status;
}

/** Public estimate view — everything the CustomerView page renders. */
app.get('/estimate/:token', async (c) => {
  const token = c.req.param('token');
  if (!TOKEN_RE.test(token)) return c.json({ error: 'Estimate not found' }, 404);

  const sb = createSupabaseAdmin(c.env);
  const order = await loadByToken(sb, token);
  if (!order) return c.json({ error: 'Estimate not found' }, 404);
  const status = await effectiveStatus(sb, order);

  const { data: company } = await sb
    .from('company_settings')
    .select(
      'company_name, logo_url, email, phone, address, hst_number, ' +
      'etransfer_email, etransfer_instructions'
    )
    .eq('id', 1)
    .single();

  // Money is computed here, never accepted from or trusted to the
  // client (AI_GUIDELINES rule 1). Only the two aggregates cross the
  // wire — the payments ledger itself stays private.
  const amountPaid = sumPayments(order.payments);

  // Sanitized payload: only what the customer page needs.
  return c.json({
    data: {
      status,
      order_number: order.order_number,
      order_date: order.order_date,
      expiry_date: order.expiry_date,
      subtotal: order.subtotal,
      discount_amount: order.discount_amount,
      taxable_amount: order.taxable_amount,
      tax_rate: order.tax_rate,
      tax_amount: order.tax_amount,
      total: order.total,
      amount_paid: amountPaid,
      balance: Number(order.total) - amountPaid,
      terms: order.terms_snapshot ?? '',
      confirmed_at: order.confirmed_at,
      cancel_requested_at: order.cancel_requested_at ?? null,
      customer: {
        first_name: order.customer?.first_name ?? '',
        last_name: order.customer?.last_name ?? '',
        shipping_address_line1: order.customer?.shipping_address_line1 ?? '',
        shipping_address_line2: order.customer?.shipping_address_line2 ?? '',
        shipping_city: order.customer?.shipping_city ?? '',
        shipping_province: order.customer?.shipping_province ?? '',
        shipping_postal_code: order.customer?.shipping_postal_code ?? '',
      },
      company,
      line_items: (order.line_items ?? []).map((li: Record<string, unknown>) => ({
        item_type: li.item_type,
        room_name: li.room_name,
        blinds_type: li.blinds_type,
        panels: li.panels,
        height_cm: li.height_cm,
        material_name: li.material_name,
        cassette_name: li.cassette_name,
        control_name: li.control_name,
        color: li.color,
        description: li.description,
        note: li.note,
        quantity: li.quantity,
        unit_price: li.unit_price,
        line_total: li.line_total,
      })),
    },
  });
});

/**
 * Customer confirm — succeeds exactly once, moving the order
 * sent → awaiting_payment.
 * 404 unknown token · 409 already confirmed · 410 expired · 400 draft.
 */
app.post('/estimate/:token/confirm', async (c) => {
  const token = c.req.param('token');
  if (!TOKEN_RE.test(token)) return c.json({ error: 'Estimate not found' }, 404);

  const sb = createSupabaseAdmin(c.env);
  const order = await loadByToken(sb, token);
  if (!order) return c.json({ error: 'Estimate not found' }, 404);

  const status = await effectiveStatus(sb, order);
  if (status === 'expired') {
    return c.json({ error: 'This estimate has expired. Please contact us for a new quote.' }, 410);
  }
  if (status !== 'sent') {
    // Anything past 'sent' (awaiting_payment / in_progress / completed)
    // has already been confirmed.
    return c.json({ error: 'This estimate has already been confirmed.' }, 409);
  }

  // Guard the transition at the DB level too: only a 'sent' row updates,
  // so two racing confirms produce exactly one winner.
  const { data: updated, error } = await sb
    .from('orders')
    .update({ status: 'awaiting_payment', confirmed_at: new Date().toISOString() })
    .eq('id', order.id)
    .eq('status', 'sent')
    .select('id, total, order_number')
    .maybeSingle();
  if (error) return c.json({ error: error.message }, 500);
  if (!updated) return c.json({ error: 'This estimate has already been confirmed.' }, 409);

  // Internal notification — best effort, never blocks the customer.
  try {
    const { data: company } = await sb
      .from('company_settings')
      .select('email, company_name')
      .eq('id', 1)
      .single();
    if (company?.email) {
      await sendEmail(c.env, {
        to: company.email,
        subject: `✅ Estimate ${updated.order_number} confirmed`,
        html: buildConfirmationNoticeHtml({
          orderNumber: updated.order_number,
          customerName: `${order.customer?.first_name ?? ''} ${order.customer?.last_name ?? ''}`.trim(),
          total: Number(updated.total),
        }),
      });
    }
  } catch (e) {
    console.error('Confirmation notification failed:', e);
  }

  return c.json({ data: { status: 'awaiting_payment', total: Number(updated.total) } });
});

/* ------------------------------------------------------------------ */
/* Cancellation requests (customer asks, staff answers)                */
/* ------------------------------------------------------------------ */

/**
 * Customer asks for their confirmation to be cancelled.
 *
 * This changes NO order status — it only raises `cancel_requested_at`,
 * which surfaces as a red banner on the staff order page. Undoing a
 * confirmation stays a user-only action.
 *
 * Accepted only while the order is `awaiting_payment` with zero
 * payments — precisely the window in which `/api/orders/:id/unconfirm`
 * would still succeed, so staff can never be handed a request they are
 * unable to grant. The status half of that rule is re-applied as a DB
 * guard on the UPDATE, so a payment landing mid-request cannot slip past
 * the read-then-write gap.
 *
 * 404 unknown token · 409 wrong status, payment already recorded, or a
 * request already open (which also makes a double tap idempotent and
 * stops duplicate staff notifications).
 */
app.post('/estimate/:token/cancel-request', async (c) => {
  const token = c.req.param('token');
  if (!TOKEN_RE.test(token)) return c.json({ error: 'Estimate not found' }, 404);

  const body = (await c.req.json().catch(() => ({}))) as { note?: unknown };
  const note = typeof body.note === 'string' ? body.note.slice(0, 500) : '';

  const sb = createSupabaseAdmin(c.env);
  const order = await loadByToken(sb, token);
  if (!order) return c.json({ error: 'Estimate not found' }, 404);

  if (order.status !== CANCELLABLE_STATUS) {
    return c.json(
      { error: 'This order can no longer be cancelled online. Please contact us directly.' },
      409
    );
  }
  if (sumPayments(order.payments) > 0) {
    return c.json(
      { error: 'A payment has already been recorded. Please contact us directly.' },
      409
    );
  }
  if (order.cancel_requested_at) {
    return c.json({ error: 'We have already received your cancellation request.' }, 409);
  }

  const { data: updated, error } = await sb
    .from('orders')
    .update({ cancel_requested_at: new Date().toISOString(), cancel_request_note: note })
    .eq('id', order.id)
    .eq('status', CANCELLABLE_STATUS)
    .is('cancel_requested_at', null)
    .select('id')
    .maybeSingle();
  if (error) return c.json({ error: error.message }, 500);
  if (!updated) {
    return c.json({ error: 'We have already received your cancellation request.' }, 409);
  }

  await notifyCancellationRequest(c.env, order, false, note);
  return c.json({ data: { cancel_requested: true } });
});

/**
 * Customer takes back a cancellation request they already opened.
 *
 * Clears the flag and the note so the staff banner disappears. Guarded
 * on the flag being set, so a stale tab cannot clear a request that
 * staff have already answered.
 *
 * 404 unknown token · 409 when no request is open.
 */
app.post('/estimate/:token/cancel-withdraw', async (c) => {
  const token = c.req.param('token');
  if (!TOKEN_RE.test(token)) return c.json({ error: 'Estimate not found' }, 404);

  const sb = createSupabaseAdmin(c.env);
  const order = await loadByToken(sb, token);
  if (!order) return c.json({ error: 'Estimate not found' }, 404);
  if (!order.cancel_requested_at) {
    return c.json({ error: 'There is no cancellation request to withdraw.' }, 409);
  }

  const { data: updated, error } = await sb
    .from('orders')
    .update({ cancel_requested_at: null, cancel_request_note: '' })
    .eq('id', order.id)
    .not('cancel_requested_at', 'is', null)
    .select('id')
    .maybeSingle();
  if (error) return c.json({ error: error.message }, 500);
  if (!updated) {
    return c.json({ error: 'There is no cancellation request to withdraw.' }, 409);
  }

  await notifyCancellationRequest(c.env, order, true);
  return c.json({ data: { cancel_requested: false } });
});

/* ------------------------------------------------------------------ */
/* Appointment pages (both kinds; token belongs to the appointment)    */
/* ------------------------------------------------------------------ */

/** Loads an appointment (+customer +order number) by public token. */
async function loadAppointmentByToken(sb: SupabaseClient, token: string) {
  const { data } = await sb
    .from('appointments')
    .select(
      'id, kind, appointment_date, appointment_time, status, ' +
      'customer:customers(first_name, last_name), order:orders(order_number)'
    )
    .eq('public_token', token)
    .maybeSingle();
  return data as Record<string, any> | null;
}

/** Best-effort internal notice when a customer responds to a visit. */
async function notifyAppointmentResponse(
  c: { env: Env },
  appt: Record<string, any>,
  confirmed: boolean,
  note?: string
): Promise<void> {
  try {
    const sb = createSupabaseAdmin(c.env);
    const { data: company } = await sb
      .from('company_settings')
      .select('email, company_name')
      .eq('id', 1)
      .single();
    if (!company?.email) return;
    const customerName =
      `${appt.customer?.first_name ?? ''} ${appt.customer?.last_name ?? ''}`.trim();
    const isInstall = appt.kind === 'installation';
    const label = isInstall
      ? `order ${appt.order?.order_number ?? ''}`.trim()
      : customerName || 'a customer';
    const build = isInstall ? buildInstallationNoticeHtml : buildAppointmentNoticeHtml;
    await sendEmail(c.env, {
      to: company.email,
      subject: confirmed
        ? `✅ ${isInstall ? 'Installation' : 'Estimate appointment'} confirmed — ${label}`
        : `🕑 ${isInstall ? 'Installation' : 'Appointment'} time change requested — ${label}`,
      html: build({
        orderNumber: appt.order?.order_number ?? customerName,
        customerName,
        confirmed,
        note,
      }),
    });
  } catch (e) {
    console.error('Appointment notification failed:', e);
  }
}

/** Public appointment view — everything the AppointmentView page needs. */
app.get('/appointment/:token', async (c) => {
  const token = c.req.param('token');
  if (!TOKEN_RE.test(token)) return c.json({ error: 'Appointment not found' }, 404);

  const sb = createSupabaseAdmin(c.env);
  const appt = await loadAppointmentByToken(sb, token);
  if (!appt) return c.json({ error: 'Appointment not found' }, 404);

  const { data: company } = await sb
    .from('company_settings')
    .select('company_name, logo_url, email, phone')
    .eq('id', 1)
    .single();

  // Sanitized payload: only what the appointment page needs.
  return c.json({
    data: {
      kind: appt.kind,
      status: appt.status,
      appointment_date: appt.appointment_date,
      appointment_time: appt.appointment_time,
      // Present for installations only — estimates carry no order.
      order_number: appt.order?.order_number ?? null,
      customer_first_name: appt.customer?.first_name ?? '',
      company,
    },
  });
});

/**
 * Customer confirms the proposed visit window (either kind).
 * 404 unknown token · 409 when there is no proposal to confirm.
 */
app.post('/appointment/:token/confirm', async (c) => {
  const token = c.req.param('token');
  if (!TOKEN_RE.test(token)) return c.json({ error: 'Appointment not found' }, 404);

  const sb = createSupabaseAdmin(c.env);
  const appt = await loadAppointmentByToken(sb, token);
  if (!appt) return c.json({ error: 'Appointment not found' }, 404);
  if (appt.status !== 'proposed') {
    return c.json({ error: 'There is no appointment time to confirm right now.' }, 409);
  }

  const { error } = await sb
    .from('appointments')
    .update({ status: 'confirmed', confirmed_at: new Date().toISOString() })
    .eq('id', appt.id)
    .eq('status', 'proposed');
  if (error) return c.json({ error: error.message }, 500);

  await notifyAppointmentResponse(c, appt, true);
  return c.json({ data: { status: 'confirmed' } });
});

/**
 * Customer requests a different visit time (optional note, both kinds).
 * 404 unknown token · 409 when there is no active proposal.
 */
app.post('/appointment/:token/request', async (c) => {
  const token = c.req.param('token');
  if (!TOKEN_RE.test(token)) return c.json({ error: 'Appointment not found' }, 404);

  const body = (await c.req.json().catch(() => ({}))) as { note?: unknown };
  const note = typeof body.note === 'string' ? body.note.slice(0, 500) : '';

  const sb = createSupabaseAdmin(c.env);
  const appt = await loadAppointmentByToken(sb, token);
  if (!appt) return c.json({ error: 'Appointment not found' }, 404);
  if (!['proposed', 'confirmed'].includes(appt.status)) {
    return c.json({ error: 'There is no appointment time to change right now.' }, 409);
  }

  const { error } = await sb
    .from('appointments')
    .update({ status: 'change_requested', response_note: note })
    .eq('id', appt.id);
  if (error) return c.json({ error: error.message }, 500);

  await notifyAppointmentResponse(c, appt, false, note);
  return c.json({ data: { status: 'change_requested' } });
});

export default app;
